package omnivore.bookmark.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@DynamoDBTable(tableName = "bookmark")
@Getter
@Setter
@NoArgsConstructor(access = AccessLevel.PUBLIC)
public class Bookmark {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String  id;

    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private String restaurantId;

    @Builder
    public Bookmark(String userId, String restaurantId) {
        this.userId = userId;
        this.restaurantId = restaurantId;
    }
}
